adding macOS uttilities

diff --git a/.github/workflows/OS_R_tests.yaml b/.github/workflows/OS_R_tests.yaml
--- a/.github/workflows/OS_R_tests.yaml
+++ b/.github/workflows/OS_R_tests.yaml
@@ -31,14 +31,15 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
- #     - name: Install macOS Utilities
- #       if: runner.os == 'macOS'
- #       run: |
- #         brew update || echo "Homebrew update failed"
- #         brew install libomp || echo "libomp installation failed"
- #         brew install qpdf || echo "qpdf installation failed but continuing"
- #         export DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib
- #         echo "DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib" >> $GITHUB_ENV
+     # This is needed
+     - name: Install macOS Utilities
+       if: runner.os == 'macOS'
+       run: |
+         brew update || echo "Homebrew update failed"
+         brew install libomp || echo "libomp installation failed"
+         brew install qpdf || echo "qpdf installation failed but continuing"
+         export DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib
+         echo "DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib" >> $GITHUB_ENV
 
       # Set up R environment
       - uses: r-lib/actions/setup-r@v2-branch
