OS-install-no-embed

diff --git a/.github/workflows/OS_R_install_no_embed.yaml b/.github/workflows/OS_R_install_no_embed.yaml
--- a/.github/workflows/OS_R_install_no_embed.yaml
+++ b/.github/workflows/OS_R_install_no_embed.yaml
@@ -4,7 +4,7 @@ on:
   pull_request:
     branches: [ "master" ]
 
-name: OS-install-no-embed
+name: OS-Tests
 
 jobs:
   R-CMD-check:
@@ -32,14 +32,14 @@ jobs:
       - uses: actions/checkout@v3
 
      # This is needed
-#      - name: Install macOS Utilities
-#        if: runner.os == 'macOS'
-#        run: |
-#          brew update || echo "Homebrew update failed"
-#          brew install libomp || echo "libomp installation failed"
-#          brew install qpdf || echo "qpdf installation failed but continuing"
-#          export DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib
-#          echo "DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib" >> $GITHUB_ENV
+      - name: Install macOS Utilities
+        if: runner.os == 'macOS'
+        run: |
+          brew update || echo "Homebrew update failed"
+          brew install libomp || echo "libomp installation failed"
+          brew install qpdf || echo "qpdf installation failed but continuing"
+          export DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib
+          echo "DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib" >> $GITHUB_ENV
 
       # Set up R environment
       - uses: r-lib/actions/setup-r@v2-branch
@@ -124,7 +124,7 @@ jobs:
           library(devtools)
           devtools::install_github("oscarkjell/text")
           text::textrpp_install(prompt = FALSE)
-#########         text::textrpp_initialize(textEmbed_test = TRUE)
+          text::textrpp_initialize(textEmbed_test = TRUE)
         shell: Rscript {0}
 
       # Session Info
