removing: Install macOS Utilities

diff --git a/.github/workflows/OS_R_tests.yaml b/.github/workflows/OS_R_tests.yaml
--- a/.github/workflows/OS_R_tests.yaml
+++ b/.github/workflows/OS_R_tests.yaml
@@ -31,26 +31,14 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-#      # macOS-specific steps
-#      - name: Fix and Debug Homebrew Issues
-#        if: runner.os == 'macOS'
-#        run: |
-#          BREW_PREFIX=$(brew --prefix)
-#          cd "$BREW_PREFIX/Library/Taps/homebrew/homebrew-core" || echo "Skipping core tap reset"
-#          git stash -u || echo "No changes to stash"
-#          git clean -d -f || echo "No files to clean"
-#          sudo chown -R $(whoami) "$BREW_PREFIX"/*
-#          brew doctor || echo "brew doctor failed"
-#          brew config || echo "brew config failed"
-
-      - name: Install macOS Utilities
-        if: runner.os == 'macOS'
-        run: |
-          brew update || echo "Homebrew update failed"
-          brew install libomp || echo "libomp installation failed"
-          brew install qpdf || echo "qpdf installation failed but continuing"
-          export DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib
-          echo "DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib" >> $GITHUB_ENV
+ #     - name: Install macOS Utilities
+ #       if: runner.os == 'macOS'
+ #       run: |
+ #         brew update || echo "Homebrew update failed"
+ #         brew install libomp || echo "libomp installation failed"
+ #         brew install qpdf || echo "qpdf installation failed but continuing"
+ #         export DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib
+ #         echo "DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib" >> $GITHUB_ENV
 
       # Set up R environment
       - uses: r-lib/actions/setup-r@v2-branch
